### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ARK-04** [Ellie-Ringwood/CMP-1903M-OOP-A01#2]
- The code works perfectly - however, why have you decided to print the whole deck after each shuffle? Could you potentially add it as an option instead?
- The error handing is great - only why don't you also let the user know how many cards there are left in the pack?
- The comments you have are great and clear but it might be worth having more - for example, one of your switches only has one of the multiple cases commented

**Comment by Ellie-Ringwood** [comment]
Thank you so much for having a look over my code :)

I will definitely try to add an option to the menu to print the deck instead of doing it automatically and display how many cards there are left. These improvements will definitely help make the user interface easier to use and understand.

Thank you again
